#!/bin/sh
##
## population.sh
## 
## Made by Carlos Linares Lopez
## Login   <clinares@atlas>
## 
## Started on  Thu May 14 18:09:45 2015 Carlos Linares Lopez
## Last update Thu May 14 18:09:45 2015 Carlos Linares Lopez
##

# make sure the sqlite3 database does not exist. As a general rule,
# parsebot prevents overwritting files with the same name
rm -rf population.db

# generate the sqlite3 database 'population.db' with the data
# specified in 'population.dbspec' processing the data in
# 'population.data'
parsebot.py --file population.data --dbspec population.dbspec --dbname population.db

# remove the files and directories generated by parsebot. They are not
# needed for this particular demo
rm -rf config/ results/ parser.out
